# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Need a break
tagline:          'Personal blog'
description:      'Personal blog of <a href="https://twitter.com/alexblanquart" target="_blank">@alexblanquart</a>.'
url:              http://alexblanquart.github.io
baseurl:          /

author:
  name:           'Alexandre Blanquart'
  url:            https://twitter.com/alexblanquart

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
